# Advent of Code

In [13]:
import math
import numpy as np
from treelib import Node, Tree

---
### Day 1

In [14]:
def getFuelVals(input_list):
    total = 0
    for i in range(len(input_list)):
        fuel = getFuel(input_list[i])        
        while fuel > 0:
            total += fuel
            fuel = getFuel(fuel)
    return total

In [15]:
def getFuel(input_val):
    return math.floor(input_val / 3) - 2

In [16]:
f = open("day1.txt")
day1_raw_input = f.readlines()
f.close()

In [17]:
day1_input = []
for fuel in day1_raw_input:
    day1_input.append(int(fuel[:-1]))

In [18]:
print(getFuelVals(day1_input))

5055835


---
### Day 2

In [19]:
def intCode(input_list):
    new = input_list[:]
    for i in range(0, len(new), 4):
        if new[i] == 99:
            return new
        elif new[i] == 1:
            new[new[i+3]] = new[new[i+1]] + new[new[i+2]]
        elif new[i] == 2:
            new[new[i+3]] = new[new[i+1]] * new[new[i+2]]
        else:
            return new

In [20]:
f = open("day2.txt")
day2_raw_input = f.read()
f.close()

day2_input = []
new_list = day2_raw_input.split(",")
for i in new_list:
    day2_input.append(int(i))

In [21]:
day2_input[1] = 12
day2_input[2] = 2
print(intCode(day2_input))

[4484226, 12, 2, 2, 1, 1, 2, 3, 1, 3, 4, 3, 1, 5, 0, 3, 2, 6, 1, 24, 1, 5, 19, 25, 2, 6, 23, 50, 1, 27, 5, 51, 2, 9, 31, 153, 1, 5, 35, 154, 2, 6, 39, 308, 2, 6, 43, 616, 1, 5, 47, 617, 2, 9, 51, 1851, 1, 5, 55, 1852, 1, 10, 59, 1856, 1, 63, 6, 1858, 1, 9, 67, 1861, 1, 71, 6, 1863, 1, 75, 13, 1868, 2, 79, 13, 9340, 2, 9, 83, 28020, 1, 87, 5, 28021, 1, 9, 91, 28024, 2, 10, 95, 112096, 1, 5, 99, 112097, 1, 103, 9, 112100, 1, 13, 107, 112105, 2, 111, 10, 448420, 1, 115, 5, 448421, 2, 13, 119, 2242105, 1, 9, 123, 2242108, 1, 5, 127, 2242109, 2, 131, 6, 4484218, 1, 135, 5, 4484219, 1, 139, 6, 4484221, 1, 143, 6, 4484223, 1, 2, 147, 4484225, 1, 151, 5, 0, 99, 2, 14, 0, 0]


In [22]:
for i in range(0,100):
    day2_input[1] = i
    for j in range(0,100):
        day2_input[2] = j
        testVal = intCode(day2_input)[0]
        if testVal == 19690720:
            print(100 * i + j)
            break

5696


---
### Day 3

In [23]:
def get_new_points(ind, d_val, num, point):
    points_list = []
    for i in range(1, num+1):
        if ind == 0:
            if d_val == 'R':
                points_list.append((point[0]+i, point[1]))
            else:
                points_list.append((point[0]-i, point[1]))
        else:
            if d_val == 'U':
                points_list.append((point[0], point[1]+i))
            else:
                points_list.append((point[0], point[1]-i))
    return points_list

In [24]:
def wire_coords(wire_directions):
    wire_points = []
    central_point = (0,0)
    current_point = central_point
    for d in wire_directions:
        num = int(d[1:])
        if d[0] == 'R' or d[0] == 'L':
            wire_points += get_new_points(0, d[0], num, current_point)
        elif d[0] == 'U' or d[0] == 'D':
            wire_points += get_new_points(1, d[0], num, current_point)
        current_point = wire_points[-1]
    return wire_points

In [25]:
f = open('day3.txt')
day3_raw_input = f.readlines()
f.close()

In [26]:
day3_input = [line.split(",") for line in day3_raw_input]

In [27]:
wire1 = wire_coords(day3_input[0])
wire2 = wire_coords(day3_input[1])

In [28]:
def find_intersections(input1, input2):
    intersections = []
    set2 = set(input2)
    for p1 in input1:
        if p1 in set2:
            intersections.append(p1)
    return intersections

In [29]:
wire_crossing = [(0,0)] + find_intersections(wire1, wire2)

In [30]:
print(wire_crossing)

[(0, 0), (525, -543), (468, -615), (921, -1459), (1146, -1459), (1261, -1459), (1296, -1459), (1323, -1748), (1261, -1720), (1296, -1081), (1261, -1081), (1220, -1569), (921, -1763), (921, -1430), (372, -2052), (372, -1948), (372, -1877), (271, -1464), (-361, -656), (-845, -656), (-196, -1028), (-315, -846), (-877, -656), (-1078, -548)]


In [31]:
def get_closest_intersection(intersections):
    central = intersections[0]
    s_d = 1000000000000000
    s_p = (0,0)
    for p in intersections[1:]:
        curr_d = abs(p[0])+abs(p[1])
        if curr_d < s_d:
            s_d = curr_d
            s_p = p
    return (s_d, s_p)

In [32]:
get_closest_intersection(wire_crossing)

(1017, (-361, -656))

In [33]:
def get_smallest_steps(intersections, input1, input2):
    central = intersections[0]
    s_steps = 1000000000
    s_p = (0,0)
    
    for p in intersections[1:]:
        curr_steps = input1.index(p) + input2.index(p) + 2
        #print(curr_steps)
        if curr_steps < s_steps:
            s_steps = curr_steps
            s_p = p
    return (s_steps, s_p)

In [34]:
get_smallest_steps(wire_crossing, wire1, wire2)

(11432, (525, -543))

---
### Day 4

In [35]:
def passwordCracker(lower, upper):
    all_poss = []
    for i in range(lower, upper):
        all_poss.append(str(i))
    
    filter_decreasing = []
    for num in all_poss:
        passed = True
        for i in range(len(num)-1):
            if int(num[i]) > int(num[i+1]):
                passed = False
        if passed:
            filter_decreasing.append(num)
    
    filter_double = set()
    for num in filter_decreasing:
        passed = False
        for i in range(len(num)-1):
            if num[i] == num[i+1]:
                passed = True
                filter_double.add(num)
                break
        
    return filter_double


In [36]:
output1 = passwordCracker(123257, 647015)

In [37]:
print(len(output1))

2220


In [38]:
def passwordCracker2(prev_output):
    filter_just_double = set()
    for num in prev_output:
        passed = False
        for i in range(len(num)-1):
            if i == 0:
                if num[i] == num[i+1] and num[i] != num[i+2]:
                    passed = True
            elif i == len(num)-2:
                if num[i] == num[i+1] and num[i-1] != num[i]:
                    passed = True
            else:
                if num[i] == num[i+1] and num[i-1] != num[i] and num[i+2] != num[i]:
                    passed = True
            if passed:
                filter_just_double.add(num)
                break
    return filter_just_double

In [39]:
output2 = passwordCracker2(list(output1))

In [40]:
print(len(output2))

1515


---
### Day 5

In [41]:
def intCode2(input_list, input_val):
    new = input_list[:]
    i = 0
    while i < len(new):
        if new[i] < 100: 
            instructs = new[i]
            if new[i+1] < len(new):
                param1 = new[new[i+1]]
            if new[i+2] < len(new):
                param2 = new[new[i+2]]
            param3 = new[i+3]
        else:
            # 001--
            if 100 < new[i] < 1000:
                instructs = new[i] - 100
                param1 = new[i+1]
                if new[i+2] < len(new):
                    param2 = new[new[i+2]]
                param3 = new[i+3]
            # 010--
            elif 1000 < new[i] < 1100:
                instructs = new[i] - 1000
                param1 = new[new[i+1]]
                param2 = new[i+2]
                param3 = new[i+3]
            # 011--
            elif 1100 < new[i] < 1200:
                instructs = new[i] - 1100
                param1 = new[i+1]
                param2 = new[i+2]
                param3 = new[i+3]
                
        if instructs == 99:
            break
        elif instructs == 1:
            new[param3] = param1 + param2
            i += 4
        elif instructs == 2:
            new[param3] = param1 * param2
            i += 4
        elif instructs == 3:
            new[new[i+1]] = input_val
            i += 2
        elif instructs == 4:
            print(param1)
            i += 2
        elif instructs == 5:
            if param1 != 0:
                i = param2
            else:
                i += 3
        elif instructs == 6:
            if param1 == 0:
                i = param2
            else:
                i += 3
        elif instructs == 7:
            if param1 < param2:
                new[param3] = 1
            else:
                new[param3] = 0
            i += 4
        elif instructs == 8:
            if param1 == param2:
                new[param3] = 1
            else:
                new[param3] = 0
            i += 4

In [42]:
f = open("day5.txt")
day5_raw_input = f.read()
f.close()

day5_input = []
new_list = day5_raw_input.split(",")
for i in new_list:
    day5_input.append(int(i))

In [43]:
#intCode2(day5_input, 5)

---
### Day 6

In [44]:
f = open('day6.txt')
day6_raw_input = f.readlines()
f.close()
day6_input = []
for line in day6_raw_input:
    line1 = line[:-1]
    day6_input.append(line1.split(')'))

In [45]:
tree = Tree()
tree.create_node("COM", "COM", data=0)

Node(tag=COM, identifier=COM, data=0)

In [46]:
for i in day6_input:
    if i[0] not in tree:
        tree.create_node(i[0], i[0], parent="COM")

In [47]:
for j in day6_input:
    if j[1] in tree:
        tree.move_node(j[1], j[0])
    else:
        tree.create_node(j[1], j[1], parent=j[0])

In [48]:
visited = set()
total_depth = 0
for i in day6_input:
    if i[0] not in visited:
        total_depth += tree.depth(i[0])
        visited.add(i[0])
    if i[1] not in visited:
        total_depth += tree.depth(i[1])
        visited.add(i[1])
print(total_depth)

314247


In [49]:
lowest_level = 0
LCA = "COM"
for i in day6_input:
    if tree.is_ancestor(i[0], "YOU") and tree.is_ancestor(i[0], "SAN"):
        if tree.level(i[0]) > lowest_level:
            lowest_level = tree.level(i[0])
            LCA = i[0]
print(lowest_level, LCA)
print(tree.level("YOU"), "YOU")
print(tree.level("SAN"), "SAN")

52 KPS
278 YOU
342 SAN


In [50]:
(277-52)+(341-52)

514

---
### Day 7

In [51]:
def intCode3(input_list, input_val1, input_val2=None, last_instruct=0):
    used_first_input = False
    new = input_list[:]
    i = last_instruct
    output = 0
    while i < len(new)-1:
        if new[i] < 100: 
            instructs = new[i]
            if new[i+1] < len(new):
                param1 = new[new[i+1]]
            if new[i+2] < len(new):
                param2 = new[new[i+2]]
            if i+3 < len(new):
                param3 = new[i+3]
        else:
            # 001--
            if 100 < new[i] < 1000:
                instructs = new[i] - 100
                param1 = new[i+1]
                if new[i+2] < len(new):
                    param2 = new[new[i+2]]
                param3 = new[i+3]
            # 010--
            elif 1000 < new[i] < 1100:
                instructs = new[i] - 1000
                param1 = new[new[i+1]]
                param2 = new[i+2]
                param3 = new[i+3]
            # 011--
            elif 1100 < new[i] < 1200:
                instructs = new[i] - 1100
                param1 = new[i+1]
                param2 = new[i+2]
                param3 = new[i+3]
                
        if instructs == 99:
            if output == 0:
                return (input_val1, None, new)
            else:
                return (output, None, new)
        elif instructs == 1:
            new[param3] = param1 + param2
            i += 4
        elif instructs == 2:
            new[param3] = param1 * param2
            i += 4
        elif instructs == 3:
            if not used_first_input:
                new[new[i+1]] = input_val1
                used_first_input = True
            else:
                new[new[i+1]] = input_val2
            i += 2
        elif instructs == 4:
            return (param1, i+2, new)
        elif instructs == 5:
            if param1 != 0:
                i = param2
            else:
                i += 3
        elif instructs == 6:
            if param1 == 0:
                i = param2
            else:
                i += 3
        elif instructs == 7:
            if param1 < param2:
                new[param3] = 1
            else:
                new[param3] = 0
            i += 4
        elif instructs == 8:
            if param1 == param2:
                new[param3] = 1
            else:
                new[param3] = 0
            i += 4
    return None

In [52]:
day7_input = [3,8,1001,8,10,8,105,1,0,0,21,42,51,76,93,110,191,272,353,434,99999,3,9,1002,9,2,9,1001,9,3,9,1002,9,3,9,1001,9,2,9,4,9,99,3,9,1002,9,3,9,4,9,99,3,9,1002,9,4,9,101,5,9,9,1002,9,3,9,1001,9,4,9,1002,9,5,9,4,9,99,3,9,1002,9,5,9,101,3,9,9,102,5,9,9,4,9,99,3,9,1002,9,5,9,101,5,9,9,1002,9,2,9,4,9,99,3,9,1002,9,2,9,4,9,3,9,1002,9,2,9,4,9,3,9,101,2,9,9,4,9,3,9,1001,9,2,9,4,9,3,9,1001,9,1,9,4,9,3,9,101,1,9,9,4,9,3,9,1001,9,1,9,4,9,3,9,102,2,9,9,4,9,3,9,1001,9,2,9,4,9,3,9,101,1,9,9,4,9,99,3,9,1001,9,1,9,4,9,3,9,1001,9,2,9,4,9,3,9,101,2,9,9,4,9,3,9,102,2,9,9,4,9,3,9,1001,9,1,9,4,9,3,9,1002,9,2,9,4,9,3,9,1001,9,2,9,4,9,3,9,102,2,9,9,4,9,3,9,101,1,9,9,4,9,3,9,1002,9,2,9,4,9,99,3,9,1002,9,2,9,4,9,3,9,1002,9,2,9,4,9,3,9,101,2,9,9,4,9,3,9,101,1,9,9,4,9,3,9,101,2,9,9,4,9,3,9,1002,9,2,9,4,9,3,9,102,2,9,9,4,9,3,9,1002,9,2,9,4,9,3,9,1002,9,2,9,4,9,3,9,1002,9,2,9,4,9,99,3,9,1002,9,2,9,4,9,3,9,102,2,9,9,4,9,3,9,1001,9,2,9,4,9,3,9,1002,9,2,9,4,9,3,9,1001,9,1,9,4,9,3,9,1002,9,2,9,4,9,3,9,1001,9,1,9,4,9,3,9,1001,9,1,9,4,9,3,9,102,2,9,9,4,9,3,9,1001,9,1,9,4,9,99,3,9,1002,9,2,9,4,9,3,9,102,2,9,9,4,9,3,9,102,2,9,9,4,9,3,9,1001,9,2,9,4,9,3,9,102,2,9,9,4,9,3,9,1002,9,2,9,4,9,3,9,1001,9,1,9,4,9,3,9,101,2,9,9,4,9,3,9,101,1,9,9,4,9,3,9,102,2,9,9,4,9,99]

In [53]:
def permutation(input_list):
    return_list = []
    
    if len(input_list) == 0:
        return []
    if len(input_list) == 1:
        return [input_list]
    
    for i in range(len(input_list)):
        m = input_list[i]
        remaining = input_list[:i] + input_list[i+1:]
        
        for p in permutation(remaining):
            return_list.append([m] + p)
    
    return return_list

In [54]:
poss_perms = permutation([5,6,7,8,9])

In [55]:
def testPerm(poss_list, day7_input_list):
    prev_output = [(0,0,day7_input_list), (0,0,day7_input_list), (0,0,day7_input_list),
                   (0,0,day7_input_list), (0,0,day7_input_list)]
    for i in range(len(poss_list)):
        prev_output[i] = intCode3(prev_output[i][2], poss_list[i], input_val2=prev_output[i][0])
        if i+1 < len(poss_list):
            prev_output[i+1] = (prev_output[i][0], prev_output[i+1][1], prev_output[i+1][2])
        else:
            prev_output[0] = (prev_output[i][0], prev_output[0][1], prev_output[0][2])
    while True:
        for i in range(len(poss_list)):
            temp = intCode3(prev_output[i][2], prev_output[i][0], last_instruct=prev_output[i][1])
            #print(temp[0])
            if temp != None and temp[1] != None:
                prev_output[i] = temp
                if temp[1] > len(day7_input_list)-2 and prev_output[i][2][temp[1]] != 99:
                    prev_output[i] = (temp[0], 0, temp[2])
                if i+1 < len(poss_list):
                    prev_output[i+1] = (prev_output[i][0], prev_output[i+1][1], prev_output[i+1][2])
                else:
                    prev_output[0] = (prev_output[i][0], prev_output[0][1], prev_output[0][2])
            else:
                return (poss_list, prev_output[-1][0])
    return (poss_list, prev_output[-1][0])

In [56]:
example = [3,26,1001,26,-4,26,3,27,1002,27,2,27,1,27,26,27,4,27,1001,28,-1,28,1005,28,6,99,0,0,5]
test_input = [9,8,7,6,5]
testPerm(test_input, example)

([9, 8, 7, 6, 5], 139629729)

In [57]:
overall_list = []
for poss in poss_perms:
    overall_list.append(testPerm(poss, day7_input))

In [58]:
overall_list.sort(key=lambda x:x[1], reverse=True)

In [59]:
#overall_list

---
### Day 8

In [60]:
f = open('day8.txt')
day8_raw_input = f.read()
f.close()

In [61]:
dim = (25,6)
day8_input = [int(char) for char in day8_raw_input]

In [62]:
day8_array = np.array(day8_input)

In [63]:
day8_array.shape = (int(len(day8_input) / (25*6)), 6*25)

In [64]:
num_not_zeros = []
for i in range(len(day8_array)):
    num_not_zeros.append((i,len(np.nonzero(day8_array[i])[0])))
num_not_zeros.sort(reverse=True, key=lambda x:x[1])
print(num_not_zeros)    

[(5, 142), (4, 141), (10, 140), (15, 140), (16, 140), (18, 140), (1, 139), (2, 139), (14, 139), (38, 139), (6, 138), (8, 138), (11, 138), (20, 138), (3, 137), (7, 137), (12, 137), (17, 137), (19, 137), (23, 137), (33, 137), (9, 136), (28, 135), (29, 135), (43, 135), (21, 134), (24, 134), (26, 134), (31, 134), (32, 134), (25, 133), (34, 133), (37, 133), (39, 133), (13, 132), (36, 132), (42, 132), (27, 131), (44, 131), (65, 130), (0, 129), (22, 129), (30, 129), (45, 129), (58, 128), (41, 127), (52, 127), (48, 126), (81, 126), (35, 125), (50, 125), (40, 124), (46, 124), (53, 124), (66, 124), (59, 123), (70, 123), (75, 123), (55, 122), (57, 122), (51, 121), (56, 121), (68, 121), (49, 120), (63, 120), (71, 120), (77, 120), (85, 120), (47, 119), (60, 119), (64, 119), (69, 119), (54, 118), (73, 118), (67, 117), (86, 117), (89, 117), (61, 116), (72, 116), (91, 116), (93, 116), (74, 115), (76, 115), (87, 115), (80, 113), (62, 112), (83, 112), (95, 112), (79, 111), (88, 109), (90, 109), (92, 107

In [65]:
num_ones = 0
num_twos = 0
for i in day8_array[5]:
    if i == 1: num_ones += 1
    elif i == 2: num_twos += 1
print(num_ones * num_twos)

1072


In [66]:
new_array = np.full(6*25, 2)

In [67]:
for array in day8_array:
    for i in range(len(array)):
        if new_array[i] == 2:
            new_array[i] = array[i]

In [68]:
for i in range(0, len(new_array), 25):
    print(new_array[i:i+25])

[1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 1 1 1 0 0 0 0 1 1 0]
[1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0]
[0 1 0 1 0 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 0]
[0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0]
[0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0]
[0 0 1 0 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0]


In [69]:
#YLFPJ

---
### Day 9

In [142]:
f = open("day9.txt")
day9_raw_input = f.read()
f.close()

day9_input = []
new_list9 = day9_raw_input.split(",")
for i in new_list9:
    day9_input.append(int(i))

In [160]:
def intCode4(input_list, input_val):
    new = {n:input_list[n] for n in range(len(input_list))}
    extra_values = []
    i = 0
    relative_base = 0
    length = len(list(new.keys()))
    while i < length:
        #print(i)
        if new[i] < 100: 
            instructs = new[i]
            if i+1 in new:
                if new[i+1] not in new:
                    new[new[i+1]] = 0
                param1 = new[new[i+1]]
            else:
                new[i+1] = 0
                param1 = new[new[i+1]]
                
            if i+2 in new:
                if new[i+2] not in new:
                    new[new[i+2]] = 0
                param2 = new[new[i+2]]
            else:
                new[i+2] = 0
                param2 = new[new[i+2]]
              
            if i+3 in new:
                param3 = new[i+3]
            else:
                new[i+3] = 0
                param3 = new[i+3]
        else:
            p = str(new[i])
            if len(p) < 4:
                p = '00' + p
            elif len(p) < 5:
                p = '0' + p 
            #print(p)
                
            instructs = int(p[-2:])
            
            # PARAM1
            # --0--
            if p[2] == '0':
                if new[i+1] not in new:
                    new[new[i+1]] = 0
                param1 = new[new[i+1]]
            # --1--
            elif p[2] == '1':
                param1 = new[i+1]
            # --2--
            elif p[2] == '2':
                if p[4] == '3':
                    param1 = relative_base + new[i+1]
                else:
                    if relative_base + new[i+1] not in new:
                        new[relative_base + new[i+1]] = 0
                    param1 = new[relative_base + new[i+1]]
            
            # PARAM2
            # -0---
            if p[1] == '0':
                if new[i+2] not in new:
                    new[new[i+2]] = 0
                param2 = new[new[i+2]]
            # -1---
            elif p[1] == '1':
                param2 = new[i+2]
            # -2---
            elif p[1] == '2':
                if relative_base + new[i+2] not in new:
                    new[relative_base + new[i+2]] = 0   
                param2 = new[relative_base + new[i+2]]
            
            # PARAM3
            # 0----
            if p[0] == '0':
                if i+3 not in new:
                    new[i+3] = 0
                param3 = new[i+3]
            # 1----
            elif p[0] == '1':
                param3 = i+3
            # 2----
            elif p[0] == '2':
                param3 = relative_base + new[i+3]
        
        length = len(list(new.keys()))
        
        if instructs == 99:
            break
        elif instructs == 1:
            new[param3] = param1 + param2
            i += 4
        elif instructs == 2:
            new[param3] = param1 * param2
            i += 4
        elif instructs == 3:
            new[param1] = input_val
            i += 2
        elif instructs == 4:
            print(param1)
            i += 2
        elif instructs == 5:
            if param1 != 0:
                i = param2
            else:
                i += 3
        elif instructs == 6:
            if param1 == 0:
                i = param2
            else:
                i += 3
        elif instructs == 7:
            if param1 < param2:
                new[param3] = 1
            else:
                new[param3] = 0
            i += 4
        elif instructs == 8:
            if param1 == param2:
                new[param3] = 1
            else:
                new[param3] = 0
            i += 4
        elif instructs == 9:
            relative_base += param1
            i += 2

In [161]:
intCode4(day9_input, 1)

2890527621


In [162]:
intCode4(day9_input, 2)

66772


---
### Day 10

In [163]:
# slopes of asteroids from current testing point

In [187]:
f = open('day10.txt')
day10_raw_input = f.readlines()
f.close()

day10_input = []
for row in day10_raw_input:
    day10_input.append([r for r in row[:-1]])

In [188]:
day10_dict = {}
height = len(day10_input)
width = len(day10_input[0])
for i in range(height):
    for j in range(width):
        day10_dict[(j,i)] = day10_input[i][j]